services:
  # Zookeeper - Gerenciador de coordenação do Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-spark-network

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092,EXTERNAL://bore.pub:18211
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,EXTERNAL://0.0.0.0:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - kafka-spark-network
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5

  # Producer Python
  python-producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: python-producer
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka-spark-network
    environment:
      KAFKA_BROKER: kafka:9092

  # Spark Container (para desenvolvimento manual)
  spark-dev:
    build:
      context: ./spark-consumer
      dockerfile: Dockerfile
    container_name: spark-dev
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka-spark-network
    environment:
      SPARK_MASTER_URL: local[*]
      KAFKA_BROKER: kafka:9092
    ports:
      - "4040:4040"  # Spark UI
    volumes:
      - ./spark-consumer:/app  # Monta a pasta local no container
    stdin_open: true
    tty: true
    command: tail -f /dev/null  # Mantém o container rodando sem executar nada

networks:
  kafka-spark-network:
    driver: bridge
